/**
 * Sparkle Hostel - Database Types
 * 
 * TypeScript interfaces for all database entities
 * Note: IDs are always strings (auto-generated by Supabase)
 * Boolean fields from SQLite are returned as "0"/"1" strings
 */

// ============== ENUMS ==============

export type UserRole = 'student' | 'warden'

export type SlotStatus = 'booked' | 'waiting' | 'cancelled'

export type LaundryOrderStatus = 'pending' | 'washing' | 'ready' | 'delivered'

export type PaymentStatus = 'unpaid' | 'pending_approval' | 'paid'

export type UrgentRequestStatus = 'open' | 'fulfilled' | 'cancelled'

// ============== LAUNDRY PRICING ==============

export const LAUNDRY_PRICING: Record<string, number> = {
  'shirt': 15,
  't-shirt': 15,
  'kurta': 15,
  'top': 15,
  'pant': 15,
  'legins': 15,
  'jeans': 20,
  'saree': 20,
  'blouse': 20,
  'bedsheet': 25,
  'pillow_cover': 25,
  'blanket': 40,
  'bath_towel': 40,
} as const

export type LaundryItem = keyof typeof LAUNDRY_PRICING

export interface LaundryItemCount {
  item: LaundryItem
  count: number
}

// ============== USER ==============

export interface User {
  id: string
  email: string
  name: string
  roomNumber: string | null
  branch: string | null
  semester: string | null
  role: UserRole
  profilePic: string | null
  createdAt: string
  updatedAt: string
}

// For creating/updating users
export interface CreateUserInput {
  id?: string
  email: string
  name: string
  roomNumber?: string
  branch?: string
  semester?: string
  role?: UserRole
  profilePic?: string
}

export interface UpdateUserInput {
  name?: string
  roomNumber?: string
  branch?: string
  semester?: string
  role?: UserRole
  profilePic?: string
}

// ============== SLOT ==============

export interface Slot {
  id: string
  date: string
  startTime: string
  stoneId: number
  userId: string | null
  status: SlotStatus
  createdAt: string
  updatedAt: string
}

export interface CreateSlotInput {
  id?: string
  date: string
  startTime: string
  stoneId: number
  userId?: string
  status?: SlotStatus
}

export interface UpdateSlotInput {
  userId?: string | null
  status?: SlotStatus
}

// ============== LAUNDRY ORDER ==============

export interface LaundryOrder {
  id: string
  userId: string
  itemsJson: string // JSON string of LaundryItemCount[]
  totalPrice: number
  status: LaundryOrderStatus
  paymentStatus: PaymentStatus
  createdAt: string
  updatedAt: string
}

// Parse items_json to get actual array
export function parseLaundryItems(itemsJson: string): LaundryItemCount[] {
  try {
    return JSON.parse(itemsJson) as LaundryItemCount[]
  } catch {
    return []
  }
}

// Create items_json from array
export function stringifyLaundryItems(items: LaundryItemCount[]): string {
  return JSON.stringify(items)
}

export interface CreateLaundryOrderInput {
  id?: string
  userId: string
  items: LaundryItemCount[]
  totalPrice?: number
  status?: LaundryOrderStatus
  paymentStatus?: PaymentStatus
}

// Calculate total price from items
export function calculateTotalPrice(items: LaundryItemCount[]): number {
  return items.reduce((total, { item, count }) => {
    const price = LAUNDRY_PRICING[item] ?? 0
    return total + (price * count)
  }, 0)
}

export interface UpdateLaundryOrderInput {
  items?: LaundryItemCount[]
  totalPrice?: number
  status?: LaundryOrderStatus
  paymentStatus?: PaymentStatus
}

// ============== URGENT REQUEST ==============

export interface UrgentRequest {
  id: string
  userId: string
  message: string
  slotId: string | null
  status: UrgentRequestStatus
  createdAt: string
  updatedAt: string
}

export interface CreateUrgentRequestInput {
  id?: string
  userId: string
  message: string
  slotId?: string
  status?: UrgentRequestStatus
}

export interface UpdateUrgentRequestInput {
  message?: string
  slotId?: string | null
  status?: UrgentRequestStatus
}

// ============== FILTER TYPES ==============

export interface SlotFilters {
  date?: string
  stoneId?: number
  userId?: string
  status?: SlotStatus
}

export interface LaundryOrderFilters {
  userId?: string
  status?: LaundryOrderStatus
  paymentStatus?: PaymentStatus
}

export interface UrgentRequestFilters {
  userId?: string
  status?: UrgentRequestStatus
  slotId?: string
}
